baseURL = "https://bunny-thief.github.io"
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = "Test Blog"
author = "bunny-thief"
description = "A test blog"
profilePicture = "images/tb_profile_20220128_234817.jpg"
mainSections = ["blog"]
